config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "static_pages#home"
  # Static Pages
  get 'static_pages/home'
  get 'static_pages/about'

  # Resources
  resources :days do
    resources :activities
    resources :reviews, only: [:new, :create]
  end

end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  address     :string
#  time        :datetime
#  cost        :float
#  hardness    :integer
#  duration    :float
#  day_id      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Activity < ActiveRecord::Base
  belongs_to :day

  validates_presence_of :name, :address, :time, :duration, :day_id

  def finish_time
    self.time + self.duration * 60 * 60
  end

end

app/models/day.rb
# == Schema Information
#
# Table name: days
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  location    :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Day < ActiveRecord::Base
  has_many :activities, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user

  validates_presence_of :name, :description, :location, :user_id

  def self.search(query)
    query = query.downcase
    where('LOWER(location) like ?', "%#{query}%")
  end

  def total_time
    self.activities.inject(0) { |sum, activity| sum + activity.duration}
  end

  def total_cost
    self.activities.inject(0) { |total, activity| total + activity.cost }
  end

  def average_difficulty
    self.activities.inject(0) { |sum, activity| sum + (activity.hardness || 0) } / self.activities.count
  end

  def average_rating
    self.reviews.inject(0) { |sum, review| sum + review.rating } / self.reviews.count.to_f
  end

end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id          :integer          not null, primary key
#  description :text
#  rating      :integer
#  day_id      :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :day

  validates_presence_of :rating, :description, :day_id, :user_id
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  username               :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :days
  has_many :reviews, dependent: :destroy

  def reviewed?(day)
    found = false
    self.reviews.each do |review|
      found = true if review.day_id = id
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :get_day, only: [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_user!

  def new
    @activity = @day.activities.new
    @activity.day_id = @day.id
  end

  def create
    @activity = @day.activities.create(activity_params)
    if @activity.save
      redirect_to day_path(@day)
    else
      render "new"
    end
  end

  def edit
    @activity = get_activity
  end

  def update
    @activity = get_activity
    if @activity.update_attributes(activity_params)
      redirect_to day_path(@day), notice: "Activity was updated"
    else
      render "edit"
    end
  end

  def destroy
    @activity = get_activity
    @activity.destroy
    flash.notice = "Activity was deleted"
    redirect_to(:back)
  end

  private
  def get_day
      @day = Day.find(params[:day_id])
  end

  def get_activity
    @day.activities.find(params[:id])
  end

  def activity_params
    params
      .require(:activity)
      .permit(:name, :description, :address, :time, :cost, :hardness, :duration, :day_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  after_filter :store_location

  def store_location
    # store last url - this is needed for post-login redirect to whatever the user last visited.
    return unless request.get?
    if (request.path != "/users/sign_in" &&
      request.path != "/users/sign_up" &&
      request.path != "/users/password/new" &&
      request.path != "/users/password/edit" &&
      request.path != "/users/confirmation" &&
      request.path != "/users/sign_out" &&
      !request.xhr?) # don't store ajax calls
      session[:previous_url] = request.fullpath
    end
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  def after_sign_out_path_for(resource)
    :back
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/days_controller.rb
class DaysController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit]
  before_action :get_user, only: [:new, :create, :edit]
  before_action :get_day, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search]
      @days = Day.search(params["search"])
    else
      @days = Day.all
    end
  end

  def new
    @day = @user.days.new
    @day.user_id = @user.id
  end

  def create
    @day = @user.days.create(day_params)
    if @day.save
      redirect_to day_path(@day)
    else
      render "new"
    end
  end

  def show
    @activities = @day.activities.order(:time)
  end

  def edit
  end

  def update
    if @day.update_attributes(day_params)
      redirect_to day_path(@day), notice: "Day was updated"
    else
      render "edit"
    end
  end

  def destroy
    @day.destroy
    flash.notice = "Day was deleted"
    redirect_to days_path
  end

  def owner?
    current_user.id == self.user.id
  end

  private
  def day_params
    params.require(:day).permit(:name, :description, :location, :user_id)
  end

  def get_user
    @user = User.find(current_user.id)
  end

  def get_day
    @day = Day.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :get_user, only: [:new, :create]
  before_action :get_day, only: [:new, :create]
  before_action :authenticate_user!

  def new
    @review = @day.reviews.new
    @review.user_id = @user.id
    @review.day_id = @day.id
  end

  def create
    @review = @day.reviews.create(review_params)
    if @review.save
      redirect_to day_path(@day)
    else
      render "new"
    end
  end

  def edit
  end

  def destroy
  end

  private
  def get_user
    @user = User.find(current_user.id)
  end

  def get_day
    @day = Day.find(params[:day_id])
  end

  def review_params
    params.require(:review).permit(:description, :rating, :user_id, :day_id)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/activities/_add.html.erb
<%= simple_form_for @activity, :url => day_activities_path do |f| %>
  <%= f.input :name, label: "Name", placeholder: "Hike Kalalau trail" %>
  <%= f.input :address, :input_html =>{:id => 'gmaps-input-address'}, :placeholder => 'Start typing a place...' %>
  <%= f.input :time, as: :time, input_html: { min: '0', step: 15 } %>
  <%= f.input :duration, label: "Duration (hours)", placeholder: "1.5" %>
  <%= f.input :description, placeholder: "We hiked, took pictures, chilled on the beach 2 miles in" %>
  <%= f.input :cost, label: "Cost ($)", placeholder: "10" %>
  <%= f.input :hardness, collection: 0..5, as: :select, prompt: "Select Hardness" %>
  <%= link_to "Back", day_path(@day), class: "btn btn-default" %>
  <%= f.submit btn_label, class: "btn btn-primary" %>
<% end %>

app/views/activities/_edit.html.erb
<%= simple_form_for @activity, :url => day_activity_path(@day, @activity) do |f| %>
  <%= f.input :name, label: "Name", placeholder: "Hike Kalalau trail" %>
  <%= f.input :address, :input_html =>{:id => 'gmaps-input-address'}, :placeholder => 'Start typing a place...' %>
  <%= f.input :time, as: :time, input_html: { min: '0', step: 15 } %>
  <%= f.input :duration, label: "Duration (hours)", placeholder: "1.5" %>
  <%= f.input :description, placeholder: "We hiked, took pictures, chilled on the beach 2 miles in" %>
  <%= f.input :cost, label: "Cost ($)", placeholder: "10" %>
  <%= f.input :hardness, collection: 0..5, as: :select, prompt: "Select Hardness" %>
  <%= link_to "Back", day_path(@day), class: "btn btn-default" %>
  <%= f.submit btn_label, class: "btn btn-primary" %>
<% end %>

app/views/activities/edit.html.erb
<section>
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <h1>Edit <%= @day.name %></h1>
      <%= render 'edit', btn_label: "Update" %>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<section>
  <div class="container">
    <div class="col-md-12">
      <h1>Add Activity for <%= @day.name %></h1>
      <%= render "add", btn_label: "Add New Activity" %>
    </div>
  </div>
</div>

app/views/days/_form.html.erb
<%= simple_form_for @day do |f| %>
  <%= f.input :name, label: "Name", placeholder: "Best day on Kauai" %>
  <%= f.input :description, placeholder: "Active day on Kauai" %>
  <%= f.input :location, :input_html =>{:id => 'gmaps-input-address'}, :placeholder => 'Start typing a place...' %>
  <%= link_to "Back", days_path, class: "btn btn-default" %>
  <%= f.submit btn_label, class: "btn btn-primary" %>
<% end %>

app/views/days/_rating.html.erb
<% (0...rating.to_i).each do  %>
  <i class="fa fa-star text-primary"></i>
<% end %>
<% (rating.to_i...5).each do  %>
  <i class="fa fa-star-o text-primary"></i>
<% end %>

app/views/days/edit.html.erb
<section>
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <h1>Edit <%= @day.name %></h1>
      <%= render 'form', btn_label: "Update" %>
    </div>
  </div>
</div>

app/views/days/index.html.erb
<section>
  <div class="container">

    <div class="row col-md-12 text-center">
      <h1>Browse Days</h1>
    </div>

    <div class="row">
      <% @days.each do |day| %>
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="thumbnail">
          <div class="caption">
            <h4><%= day.name %></h4>
            <p><%= day.description %></p>
            <p>
              <%= link_to "View", day_path(day.id), class: "btn btn-primary btn-block" %>
            </p>
            <p>
              <i class="fa fa-usd text-success"></i><%= day.total_cost %>
              <i class="fa fa-clock-o text-primary"></i><%= day.total_time %>h
              <% if not day.reviews.empty? %>
                <i class="fa fa-star text-primary"></i><%= day.average_rating %>/5
              <% end %>
            </p>
            <p>
              <% if day.user %>
                <small>By: <b><%= day.user.username %></b></small>
              <% end %>
            </p>
          </div>
        </div>
      </div>
      <% end %>
    </div>

  </div>
</section>

app/views/days/new.html.erb
<section>
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <h1>Add Your Day</h1>
      <%= render 'form', btn_label: "Add New Day" %>
    </div>
  </div>
</div>

app/views/days/show.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1> <%= @day.name %></h1>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <p> <%= @day.description %></p>
        <% if not @day.activities.empty? %>
          <p><b>Cost:</b> <%= number_to_currency(@day.total_cost) %></p>
          <p><b>Difficulty:</b> <%= render "rating", rating: @day.average_difficulty %></p>
        <% end %>
        <% if not @day.reviews.empty? %>
          <p><b>Rating:</b> <%= render "rating", rating: @day.average_rating %></p>
        <% end %>
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
          <% @activities.each_with_index do |activity, index| %>
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="heading<%= index %>">
              <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= index %>" aria-expanded="false" aria-controls="collapseOne">
                  <%= activity.time.strftime("%I:%M %p") %> - <%= activity.name %>
                </a>
                <div class="pull-right">
                  <% if user_signed_in? && current_user.id == @day.user.id %>
                    <%= link_to edit_day_activity_path(@day, activity), class: "" do %>
                      <i class="fa fa-pencil text-primary"></i>
                    <% end %>
                    <%= link_to day_activity_path(@day, activity), method: :delete, data: { confirm: "You sure?" } do %>
                      <i class="fa fa-remove text-danger"></i>
                    <% end %>
                  <% end %>
                </div>
              </h4>
            </div>
            <div id="collapse<%= index %>" class="panel-collapse collapse <%= "in" if index == 0 %>" role="tabpanel" aria-labelledby="headingOne">
              <div class="panel-body">
                <p><%= activity.description %></p>
                <p><i class="fa fa-map-marker text-danger"></i> <%= activity.address %></p>
                <% if activity.cost %>
                  <p><i class="fa fa-usd text-success"></i> <%= activity.cost %></p>
                <% end %>
                <% if activity.duration %>
                  <p><i class="fa fa-clock-o text-primary"></i> <%= activity.duration %>h</p>
                <% end %>
                <p><% if activity.hardness %>
                  <div class="progress">
                    <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow="<%= activity.hardness %>" aria-valuemin="0" aria-valuemax="5" style="width: <%= activity.hardness * 20 %>%">
                      Difficulty<span class="sr-only"></span>
                    </div>
                  </div>
                <% end %>
                </p>
                <input type="hidden" class="address" value="<%= activity.address %>">
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <p>
          <%= social_share_button_tag( @day.name, desc: "The summary of page", :popup => "true") %>
        </p>
        <%= link_to "Back", days_path, class: "btn btn-default" %>
        <% if user_signed_in? && current_user.id == @day.user.id %>
          <%= link_to "Edit Day", edit_day_path(@day), class: "btn btn-primary" %>
          <%= link_to "Add Activity", new_day_activity_path(@day), class: "btn btn-primary" %>
          <%= link_to "Delete This Day", @day, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
        <% elsif user_signed_in? && current_user.id != @day.user.id%>
          <%= link_to "Add Review", new_day_review_path(@day), class: "btn btn-primary" %>
        <% end %>
      </div>

      <div class="col-md-6">
        <div id="map" style='height: 400px;'></div>
        <p id="location"> <%= @day.location %></p>
      </div>

    </div>

    <div class="row">
      <div class="col-md-12">
        <h3>Reviews:</h3>
        <% if not @day.reviews.empty? %>
          <% @day.reviews.each do |review| %>
            <%= review.description %><br />
            <%= render "rating", rating: review.rating %><br />
            <small>Author: <b><%= review.user.username %></b></small>
            <hr>
          <% end %>
        <% else %>
          <p>No reviews yet</p>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BestDay</title>
  <script type="text/javascript" src="//maps.google.com/maps/api/js?v=3.13&amp;key=AIzaSyAvtDBy64d_40bH-WaUTbjkXWM0Uo12EEo&amp;sensor=false&amp;libraries=geometry"></script>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= controller_name %> <%= controller.action_name %>">

  <%= render 'shared/primary_nav' %>
    <div class="row col-md-4 col-md-offset-4 alerts">
      <% flash.each do |key, value| %>
      <div class="alert alert-dismissible alert-info alert-<%= key %>">
        <%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <% end %>
  </div>
  <%= yield %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for @review, :url => day_reviews_path do |f| %>
  <%= f.input :rating, collection: 1..5, as: :select, prompt: "Select Rating" %>
  <%= f.input :description, placeholder: "Active day on Kauai" %>
  <%= f.input :user_id, as: :hidden %>
  <%= link_to "Back", days_path, class: "btn btn-default" %>
  <%= f.submit btn_label, class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<section>
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <h1>Add Your Review</h1>
      <%= render 'form', btn_label: "Add Review" %>
    </div>
  </div>
</div>

app/views/shared/_primary_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="collapse-navbar">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Browse All Days", days_path %> </li>
      </ul>

      <% if controller_name == 'days' %>
        <%= form_tag(days_path, :method => "get", id: "search-form", class: "navbar-form navbar-left") do %>
          <div class="input-group">
            <%= text_field_tag :search, params[:search], :autofocus => true, placeholder: "San Francisco", class: "form-control" %>
            <span class="input-group-btn">
              <%= button_tag(type: 'submit', class: "btn btn-default") do %>
              <i class="fa fa-search"></i>
              <% end %>
            </span>
          </div>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to "Add My Day", new_day_path, class: "btn btn-primary btn-sm navbar-btn navbar-left" %>
        <% end %>
      <% end %>

      <% if user_signed_in? %>
        <%= link_to "Sign Out #{current_user.username}", destroy_user_session_path, method: :delete, class: "btn btn-default btn-sm navbar-right navbar-btn" %>
      <% else %>
      <form class="navbar-form navbar-right" role="search">
        <%= link_to "Sign In", new_user_session_path, class: "btn btn-default btn-sm" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-sm" %>
      </form>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<header>
  <div class="parallax"></div>
  <div class="header-content">
    <div class="header-content-inner">
      <h1>Find or Share Your Best Day</h1>
      <p>Look what others did and plan away!</p>

      <%= form_tag(days_path, :method => "get", id: "search-form", class: "col-md-4 col-md-offset-4") do %>
        <div class="input-group">
          <%= text_field_tag :search, params[:search], :autofocus => true, placeholder: "San Francisco", class: "form-control" %>
          <span class="input-group-btn">
            <%= button_tag(type: 'submit', class: "btn btn-default") do %>
              <i class="fa fa-search"></i>
            <% end %>
          </span>
        </div>
      <% end %>

    </div>
  </div>
</header>
<!-- <section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">About App</h2>
        <hr class="primary">
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-diamond wow bounceIn text-primary"></i>
          <h3>Sturdy Templates</h3>
          <p class="text-muted">Our templates are updated regularly so they don't break.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
          <h3>Ready to Ship</h3>
          <p class="text-muted">You can use this theme as is, or you can make changes!</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
          <h3>Up to Date</h3>
          <p class="text-muted">We update dependencies to keep things fresh.</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
          <h3>Made with Love</h3>
          <p class="text-muted">You have to make your websites with love these days!</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">Let's Get In Touch!</h2>
        <hr class="primary">
        <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
      </div>
      <div class="col-lg-4 col-lg-offset-2 text-center">
        <i class="fa fa-phone fa-3x wow bounceIn"></i>
        <p>123-456-6789</p>
      </div>
      <div class="col-lg-4 text-center">
        <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
        <p><a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a></p>
      </div>
    </div>
  </div>
</section> -->